import assert from 'node:assert/strict';
import { buildSeoHealthRoutePayload } from '@/modules/seo/application/seo-health-route-payload';

async function main() {
    const payload = buildSeoHealthRoutePayload({
        success: true,
        healthy: false,
        timestamp: '2026/5/12 上午10:00:00',
        elapsed: '4.2s',
        pages: [
            {
                name: '首頁',
                path: '/',
                status: 200,
                jsonLd: true,
                issues: [],
            },
            {
                name: '查詢空房',
                path: '/book',
                status: 500,
                jsonLd: false,
                issues: ['title missing', 'json-ld missing'],
            },
        ],
        sitemap: {
            ok: true,
            pageCount: 42,
        },
        robots: true,
        ranking: {
            totalClicks: 12,
            totalImpressions: 180,
            avgPosition: 9.4,
            avgCtr: 0.067,
            topQueries: [],
            targetKeywords: [],
            topPages: [],
            trendReport: {
                overall: { status: 'up', label: '偏進步', reason: '7d 與 28d 趨勢都偏正向' },
                comparison7d: {
                    label: '近7天',
                    current: { startDate: '2026-05-04', endDate: '2026-05-10', clicks: 12, impressions: 180, ctr: 0.067, avgPosition: 9.4 },
                    previous: { startDate: '2026-04-27', endDate: '2026-05-03', clicks: 10, impressions: 150, ctr: 0.067, avgPosition: 10.2 },
                    clicksDelta: 2,
                    clicksDeltaPct: 20,
                    impressionsDelta: 30,
                    impressionsDeltaPct: 20,
                    ctrDelta: 0,
                    positionDelta: 0.8,
                    status: 'up',
                    note: null,
                },
                comparison28d: {
                    label: '近28天',
                    current: { startDate: '2026-04-13', endDate: '2026-05-10', clicks: 42, impressions: 700, ctr: 0.06, avgPosition: 9.1 },
                    previous: { startDate: '2026-03-16', endDate: '2026-04-12', clicks: 38, impressions: 650, ctr: 0.058, avgPosition: 9.7 },
                    clicksDelta: 4,
                    clicksDeltaPct: 10.5,
                    impressionsDelta: 50,
                    impressionsDeltaPct: 7.7,
                    ctrDelta: 0.002,
                    positionDelta: 0.6,
                    status: 'up',
                    note: null,
                },
                landingPages: [],
                keywordGroups: [],
                notes: ['低搜尋量詞不直接判定出榜'],
            },
        },
        rankingError: 'gsc timeout',
        ga4: {
            measurementId: 'G-LKVWPNVH5M',
            siteTagDetected: true,
            propertyIdConfigured: false,
            oauthConfigured: true,
            dataApiStatus: 'missing_config',
            date: null,
            summary: null,
            landingPages: [],
            aiAssistants: {
                summary: null,
                sources: [],
            },
            notes: ['Google AI Overviews / AI Mode 目前仍算在 Organic Search；GA4 可單獨切出的 AI 流量是可辨識的 AI Assistants referrer。'],
            error: null,
        },
        alertSent: true,
        alertSuppressed: false,
        triggerSource: 'external-script',
        forceSend: false,
        previousAlertAt: '2026-05-11T08:00:00.000Z',
    });

    assert.deepEqual(payload, {
        success: true,
        healthy: false,
        timestamp: '2026/5/12 上午10:00:00',
        elapsed: '4.2s',
        pages: [
            {
                name: '首頁',
                path: '/',
                status: 200,
                jsonLd: true,
                issues: [],
            },
            {
                name: '查詢空房',
                path: '/book',
                status: 500,
                jsonLd: false,
                issues: ['title missing', 'json-ld missing'],
            },
        ],
        sitemap: {
            ok: true,
            pageCount: 42,
        },
        robots: true,
        ranking: {
            totalClicks: 12,
            totalImpressions: 180,
            avgPosition: 9.4,
            avgCtr: 0.067,
            topQueries: [],
            targetKeywords: [],
            topPages: [],
            trendReport: {
                overall: { status: 'up', label: '偏進步', reason: '7d 與 28d 趨勢都偏正向' },
                comparison7d: {
                    label: '近7天',
                    current: { startDate: '2026-05-04', endDate: '2026-05-10', clicks: 12, impressions: 180, ctr: 0.067, avgPosition: 9.4 },
                    previous: { startDate: '2026-04-27', endDate: '2026-05-03', clicks: 10, impressions: 150, ctr: 0.067, avgPosition: 10.2 },
                    clicksDelta: 2,
                    clicksDeltaPct: 20,
                    impressionsDelta: 30,
                    impressionsDeltaPct: 20,
                    ctrDelta: 0,
                    positionDelta: 0.8,
                    status: 'up',
                    note: null,
                },
                comparison28d: {
                    label: '近28天',
                    current: { startDate: '2026-04-13', endDate: '2026-05-10', clicks: 42, impressions: 700, ctr: 0.06, avgPosition: 9.1 },
                    previous: { startDate: '2026-03-16', endDate: '2026-04-12', clicks: 38, impressions: 650, ctr: 0.058, avgPosition: 9.7 },
                    clicksDelta: 4,
                    clicksDeltaPct: 10.5,
                    impressionsDelta: 50,
                    impressionsDeltaPct: 7.7,
                    ctrDelta: 0.002,
                    positionDelta: 0.6,
                    status: 'up',
                    note: null,
                },
                landingPages: [],
                keywordGroups: [],
                notes: ['低搜尋量詞不直接判定出榜'],
            },
        },
        rankingError: 'gsc timeout',
        ga4: {
            measurementId: 'G-LKVWPNVH5M',
            siteTagDetected: true,
            propertyIdConfigured: false,
            oauthConfigured: true,
            dataApiStatus: 'missing_config',
            date: null,
            summary: null,
            landingPages: [],
            aiAssistants: {
                summary: null,
                sources: [],
            },
            notes: ['Google AI Overviews / AI Mode 目前仍算在 Organic Search；GA4 可單獨切出的 AI 流量是可辨識的 AI Assistants referrer。'],
            error: null,
        },
        alertSent: true,
        alertSuppressed: false,
        triggerSource: 'external-script',
        forceSend: false,
        previousAlertAt: '2026-05-11T08:00:00.000Z',
    });

    console.log('✅ SEO health route payload tests passed');
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
